"""add embedding_dimension

Revision ID: 0f3dabac11ac
Revises: 3b24b1dd93b3
Create Date: 2026-07-16 05:26:27.304737

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0f3dabac11ac'
down_revision = '3b24b1dd93b3'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk_state', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk_state', 'embedding_dimension')
    # ### end Alembic commands ###
