"""Add postgres ingestion models V3

Revision ID: 3b24b1dd93b3
Revises: b7995c35a83d
Create Date: 2026-07-16 05:12:26.393000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b24b1dd93b3'
down_revision = 'b7995c35a83d'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('faction', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_index(op.f('ix_entities_canonical_name'), 'entities', ['canonical_name'], unique=True)
    op.create_table('ingestion_metrics',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('downloaded_pages', sa.Integer(), nullable=True),
    sa.Column('parsed_pages', sa.Integer(), nullable=True),
    sa.Column('parent_documents', sa.Integer(), nullable=True),
    sa.Column('child_chunks', sa.Integer(), nullable=True),
    sa.Column('embedded_chunks', sa.Integer(), nullable=True),
    sa.Column('failed_chunks', sa.Integer(), nullable=True),
    sa.Column('unknown_entities', sa.Integer(), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_ingestion_metrics'))
    )
    op.create_table('lore_parents',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('page_title', sa.String(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('markdown', sa.TEXT(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lore_parents'))
    )
    op.create_index(op.f('ix_lore_parents_page_id'), 'lore_parents', ['page_id'], unique=False)
    op.create_index(op.f('ix_lore_parents_page_title'), 'lore_parents', ['page_title'], unique=False)
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('worker', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('statistics', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_jobs'))
    )
    op.create_table('wiki_sync_state',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('page_title', sa.String(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('page_id', name=op.f('pk_wiki_sync_state'))
    )
    op.create_index(op.f('ix_wiki_sync_state_page_title'), 'wiki_sync_state', ['page_title'], unique=False)
    op.create_table('aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_aliases_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aliases'))
    )
    op.create_index(op.f('ix_aliases_alias'), 'aliases', ['alias'], unique=True)
    op.create_index(op.f('ix_aliases_entity_id'), 'aliases', ['entity_id'], unique=False)
    op.create_table('chunk_state',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('chunk_hash', sa.String(), nullable=False),
    sa.Column('embedded', sa.Boolean(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embedding_version', sa.String(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('parser_version', sa.String(), nullable=True),
    sa.Column('dictionary_version', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['lore_parents.id'], name=op.f('fk_chunk_state_parent_id_lore_parents')),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_chunk_state'))
    )
    op.create_index(op.f('ix_chunk_state_chunk_hash'), 'chunk_state', ['chunk_hash'], unique=False)
    op.create_index(op.f('ix_chunk_state_parent_id'), 'chunk_state', ['parent_id'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('fk_entity_relationships_source_entity_id_entities')),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_entity_relationships_target_entity_id_entities')),
    sa.PrimaryKeyConstraint('source_entity_id', 'target_entity_id', name=op.f('pk_entity_relationships'))
    )
    op.create_table('pipeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_jobs.id'], name=op.f('fk_pipeline_events_job_id_pipeline_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_events'))
    )
    op.create_index(op.f('ix_pipeline_events_job_id'), 'pipeline_events', ['job_id'], unique=False)
    op.drop_index(op.f('idx_discord_interactions_channel_id'), table_name='discord_interactions')
    op.drop_index(op.f('idx_discord_interactions_core_user_id'), table_name='discord_interactions')
    op.drop_index(op.f('idx_discord_interactions_created_at'), table_name='discord_interactions')
    op.drop_index(op.f('idx_discord_interactions_user_id'), table_name='discord_interactions')
    op.drop_table('discord_interactions')
    op.drop_table('emotional_states')
    op.drop_index(op.f('idx_guild_settings_channel_unique'), table_name='guild_settings')
    op.drop_table('guild_settings')
    op.drop_index(op.f('idx_discord_users_core_user_id'), table_name='discord_users')
    op.drop_index(op.f('idx_discord_users_last_seen_at'), table_name='discord_users')
    op.drop_index(op.f('idx_discord_users_uid_gid'), table_name='discord_users')
    op.drop_table('discord_users')
    op.drop_index(op.f('ix_affection_logs_created_desc'), table_name='affection_logs')
    op.drop_index(op.f('ix_affection_logs_user_id'), table_name='affection_logs')
    op.drop_table('affection_logs')
    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affection_logs',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('triggered_by_message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('delta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_message_id'], ['messages.id'], name=op.f('fk_affection_logs_triggered_by_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_affection_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_affection_logs'))
    )
    op.create_index(op.f('ix_affection_logs_user_id'), 'affection_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_affection_logs_created_desc'), 'affection_logs', ['created_at'], unique=False)
    op.create_table('discord_users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('discord_user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('core_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('discord_user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discord_user_global_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discord_user_tag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_cleared_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('discord_guild_id', sa.TEXT(), server_default=sa.text("'DM'::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('discord_users_pkey')),
    sa.UniqueConstraint('core_user_id', name=op.f('discord_users_core_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_discord_users_uid_gid'), 'discord_users', ['discord_user_id', 'discord_guild_id'], unique=True)
    op.create_index(op.f('idx_discord_users_last_seen_at'), 'discord_users', [sa.literal_column('last_seen_at DESC')], unique=False)
    op.create_index(op.f('idx_discord_users_core_user_id'), 'discord_users', ['core_user_id'], unique=False)
    op.create_table('guild_settings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('discord_guild_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chisa_channel_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('setup_by_user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('guild_settings_pkey'))
    )
    op.create_index(op.f('idx_guild_settings_channel_unique'), 'guild_settings', ['chisa_channel_id'], unique=True)
    op.create_table('emotional_states',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('affection_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mood', postgresql.ENUM('NEUTRAL', 'HAPPY', 'SHY', 'JEALOUS', 'SAD', 'EXCITED', name='mood_enum'), autoincrement=False, nullable=False),
    sa.Column('trust_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attachment_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emotional_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_emotional_states'))
    )
    op.create_table('discord_interactions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('discord_user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('core_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('discord_user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discord_user_global_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discord_user_tag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discord_guild_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discord_guild_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discord_channel_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discord_channel_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discord_message_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('command_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('assistant_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('core_request_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('core_response_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('discord_interactions_pkey'))
    )
    op.create_index(op.f('idx_discord_interactions_user_id'), 'discord_interactions', ['discord_user_id'], unique=False)
    op.create_index(op.f('idx_discord_interactions_created_at'), 'discord_interactions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_discord_interactions_core_user_id'), 'discord_interactions', ['core_user_id'], unique=False)
    op.create_index(op.f('idx_discord_interactions_channel_id'), 'discord_interactions', ['discord_channel_id'], unique=False)
    op.drop_index(op.f('ix_pipeline_events_job_id'), table_name='pipeline_events')
    op.drop_table('pipeline_events')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_chunk_state_parent_id'), table_name='chunk_state')
    op.drop_index(op.f('ix_chunk_state_chunk_hash'), table_name='chunk_state')
    op.drop_table('chunk_state')
    op.drop_index(op.f('ix_aliases_entity_id'), table_name='aliases')
    op.drop_index(op.f('ix_aliases_alias'), table_name='aliases')
    op.drop_table('aliases')
    op.drop_index(op.f('ix_wiki_sync_state_page_title'), table_name='wiki_sync_state')
    op.drop_table('wiki_sync_state')
    op.drop_table('pipeline_jobs')
    op.drop_index(op.f('ix_lore_parents_page_title'), table_name='lore_parents')
    op.drop_index(op.f('ix_lore_parents_page_id'), table_name='lore_parents')
    op.drop_table('lore_parents')
    op.drop_table('ingestion_metrics')
    op.drop_index(op.f('ix_entities_canonical_name'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
