"""add is_success to messages

Revision ID: b7995c35a83d
Revises: fb20eea4d022
Create Date: 2026-06-14 00:16:50.470398

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7995c35a83d'
down_revision = 'fb20eea4d022'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_success', sa.Boolean(), nullable=True))
    # Fill existing rows with True before setting it to NOT NULL
    op.execute("UPDATE messages SET is_success = TRUE")
    op.alter_column('messages', 'is_success', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_success')
    # ### end Alembic commands ###
