"""Add updated_at to entities

Revision ID: f2b15808286f
Revises: 0f3dabac11ac
Create Date: 2026-07-16 05:39:21.789921

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f2b15808286f'
down_revision = '0f3dabac11ac'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'updated_at')
    # ### end Alembic commands ###
