"""phase_3a_initial_schema

Revision ID: f4eea57ac3c7
Revises: 
Create Date: 2026-03-04 19:18:31.985779

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f4eea57ac3c7'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('discord_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_user_started', 'conversations', ['user_id', 'started_at'], unique=False, postgresql_where='started_at IS NOT NULL')
    op.create_table('emotional_states',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('affection_score', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Enum('NEUTRAL', 'HAPPY', 'SHY', 'JEALOUS', 'SAD', 'EXCITED', name='mood_enum'), nullable=False),
    sa.Column('trust_level', sa.Integer(), nullable=False),
    sa.Column('attachment_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emotional_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_emotional_states'))
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_created_desc', 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('affection_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by_message_id', sa.UUID(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_message_id'], ['messages.id'], name=op.f('fk_affection_logs_triggered_by_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_affection_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_affection_logs'))
    )
    op.create_index('ix_affection_logs_created_desc', 'affection_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_affection_logs_user_id'), 'affection_logs', ['user_id'], unique=False)
    op.create_table('memory_metadata',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('memory_type', sa.Enum('FACT', 'EMOTIONAL', 'EPISODIC', 'SUMMARY', name='memory_type_enum'), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('emotional_intensity', sa.Float(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], name=op.f('fk_memory_metadata_source_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memory_metadata_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_metadata'))
    )
    op.create_index('ix_memory_created_desc', 'memory_metadata', ['created_at'], unique=False)
    op.create_index(op.f('ix_memory_metadata_memory_type'), 'memory_metadata', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_metadata_user_id'), 'memory_metadata', ['user_id'], unique=False)
    op.create_index('ix_memory_type_importance', 'memory_metadata', ['memory_type', 'importance_score'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_type_importance', table_name='memory_metadata')
    op.drop_index(op.f('ix_memory_metadata_user_id'), table_name='memory_metadata')
    op.drop_index(op.f('ix_memory_metadata_memory_type'), table_name='memory_metadata')
    op.drop_index('ix_memory_created_desc', table_name='memory_metadata')
    op.drop_table('memory_metadata')
    op.drop_index(op.f('ix_affection_logs_user_id'), table_name='affection_logs')
    op.drop_index('ix_affection_logs_created_desc', table_name='affection_logs')
    op.drop_table('affection_logs')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index('ix_messages_created_desc', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('emotional_states')
    op.drop_index('ix_conversations_user_started', table_name='conversations', postgresql_where='started_at IS NOT NULL')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
