"""Create true UUID UserStats and EmotionState

Revision ID: fb20eea4d022
Revises: f4eea57ac3c7
Create Date: 2026-03-05 03:17:17.426528

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fb20eea4d022'
down_revision = 'f4eea57ac3c7'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_state',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joy', sa.Float(), nullable=False),
    sa.Column('sadness', sa.Float(), nullable=False),
    sa.Column('trust', sa.Float(), nullable=False),
    sa.Column('attachment', sa.Float(), nullable=False),
    sa.Column('irritation', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emotion_state_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_emotion_state'))
    )
    op.create_index(op.f('ix_emotion_state_user_id'), 'emotion_state', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_stats'))
    )
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_emotion_state_user_id'), table_name='emotion_state')
    op.drop_table('emotion_state')
    # ### end Alembic commands ###
