"""JWT verification adapter for web sessions and channel workload credentials."""

from __future__ import annotations

from collections.abc import Iterable
from datetime import UTC, datetime, timedelta
from typing import Any
from uuid import uuid4

from jose import JWTError, jwt

from app.config.settings import settings
from app.domain.value_objects.principal import PrincipalContext


class AuthenticationError(Exception):
    """A credential is absent, malformed, expired, or not accepted."""


class JwtAuthenticator:
    """Builds ``PrincipalContext`` only after cryptographic JWT verification."""

    _SUPPORTED_TOKEN_USES = {"web", "workload"}

    _ANONYMOUS_WEB_SCOPES = frozenset({"chat:write", "chat:read", "chat:clear"})

    def authenticate_bearer(self, authorization: str | None) -> PrincipalContext:
        if not authorization:
            raise AuthenticationError("missing bearer credential")
        scheme, separator, token = authorization.partition(" ")
        if scheme.lower() != "bearer" or not separator or not token.strip():
            raise AuthenticationError("invalid authorization scheme")
        return self.authenticate_token(token.strip())

    def authenticate_token(self, token: str) -> PrincipalContext:
        unverified = self._unverified_claims(token)
        token_use = unverified.get("token_use")
        if token_use not in self._SUPPORTED_TOKEN_USES:
            raise AuthenticationError("unsupported credential type")

        secret, issuer, expected_source = self._verification_material(str(token_use))
        try:
            claims = jwt.decode(
                token,
                secret,
                algorithms=[settings.JWT_ALGORITHM],
                audience=settings.JWT_AUDIENCE,
                issuer=issuer,
                options={"require_exp": True, "require_iat": True, "require_sub": True},
            )
        except JWTError as error:
            raise AuthenticationError("credential verification failed") from error

        if claims.get("token_use") != token_use:
            raise AuthenticationError("credential type changed during verification")
        source = claims.get("source")
        if source != expected_source:
            raise AuthenticationError("credential source is invalid")
        return self._principal_from_claims(claims, str(token_use), expected_source)

    def issue_anonymous_web_session(self, subject_id: str) -> str:
        """Issues a short-lived, least-privilege web session signed by this service.

        ``subject_id`` is generated by the application service, never supplied
        by a browser request body or header.
        """
        now = datetime.now(UTC)
        claims = {
            "sub": subject_id,
            "scopes": sorted(self._ANONYMOUS_WEB_SCOPES),
            "token_use": "web",
            "source": "web",
            "iss": settings.JWT_ISSUER,
            "aud": settings.JWT_AUDIENCE,
            "iat": now,
            "exp": now + timedelta(minutes=settings.JWT_EXPIRE_MINUTES),
            "jti": str(uuid4()),
        }
        return jwt.encode(claims, settings.JWT_SECRET, algorithm=settings.JWT_ALGORITHM)

    @staticmethod
    def _unverified_claims(token: str) -> dict[str, Any]:
        try:
            claims = jwt.get_unverified_claims(token)
        except JWTError as error:
            raise AuthenticationError("malformed credential") from error
        if not isinstance(claims, dict):
            raise AuthenticationError("malformed credential claims")
        return claims

    @staticmethod
    def _verification_material(token_use: str) -> tuple[str, str, str]:
        if token_use == "web":
            return settings.JWT_SECRET, settings.JWT_ISSUER, "web"
        return settings.DISCORD_WORKLOAD_JWT_SECRET, settings.DISCORD_WORKLOAD_JWT_ISSUER, "discord"

    @staticmethod
    def _principal_from_claims(
        claims: dict[str, Any], token_use: str, source: str
    ) -> PrincipalContext:
        subject_id = claims.get("sub")
        if not isinstance(subject_id, str) or not subject_id.strip():
            raise AuthenticationError("credential subject is invalid")

        scopes = JwtAuthenticator._scopes(claims.get("scopes"))
        if not scopes:
            raise AuthenticationError("credential scopes are missing")

        tenant_id = JwtAuthenticator._optional_string(claims.get("tenant_id"))
        channel_id = JwtAuthenticator._optional_string(claims.get("channel_id"))
        display_name = JwtAuthenticator._optional_string(claims.get("display_name"))
        return PrincipalContext(
            subject_id=subject_id,
            tenant_id=tenant_id,
            channel_id=channel_id,
            source="web" if source == "web" else "discord",
            kind="user" if token_use == "web" else "workload",
            scopes=frozenset(scopes),
            display_name=display_name,
        )

    @staticmethod
    def _scopes(value: object) -> set[str]:
        if isinstance(value, str):
            candidates: Iterable[object] = value.split()
        elif isinstance(value, list):
            candidates = value
        else:
            return set()
        return {item.strip() for item in candidates if isinstance(item, str) and item.strip()}

    @staticmethod
    def _optional_string(value: object) -> str | None:
        if value is None:
            return None
        if not isinstance(value, str) or not value.strip():
            raise AuthenticationError("credential claim is invalid")
        return value.strip()


jwt_authenticator = JwtAuthenticator()
